# Generated by Django 2.0.2 on 2018-02-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180214_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='categories',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
