# Generated by Django 2.0.2 on 2018-02-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20180214_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='like_dislike',
            field=models.BooleanField(default=False),
        ),
    ]
