# Generated by Django 2.0.2 on 2018-02-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantlocation_like_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='like_dislike',
            new_name='recommend',
        ),
    ]
