# Generated by Django 2.0.2 on 2018-02-16 11:34

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20180215_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='categories',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[restaurants.validators.validate_categories]),
        ),
    ]
