# Generated by Django 2.0.2 on 2018-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='excludes',
            field=models.TextField(blank=True, help_text='separate_by_commas', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='contents',
            field=models.TextField(default=1, help_text='separate_by_commas'),
            preserve_default=False,
        ),
    ]
